Facturation.WEB.UI/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Facturation.BLL;
using Facturation.DAL;
using Facturation.DTO;
using PagedList;

namespace Facturation.WEB.UI.Controllers
{
    [Authorize]
    public class ClientController : Controller
    {
        private ClientLogic _clientLogic;
        private ZipcodeLogic _zipcodeLogic;

        public ClientController()
        {
            _clientLogic = new ClientLogic();
            _zipcodeLogic = new ZipcodeLogic();
        }

        // GET: Client
        public ActionResult Index(string sortOrder, string searchString, string currentFilter, int? page)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            var clients = from client in _clientLogic.GetActiveClients()
                select client;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            if (!String.IsNullOrEmpty(searchString))
            {
                clients = clients.Where(s => s.Name.Contains(searchString) || s.LastName.Contains(searchString)
                                                                           || s.Email.Contains(searchString) ||
                                                                           s.Vat.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    clients = clients.OrderByDescending(s => s.Name);
                    break;
                default:
                    clients = clients.OrderBy(s => s.Name);
                    break;
            }
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(clients.ToPagedList(pageNumber, pageSize));

           
        }

        // GET: Client/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ClientDTO clientDTO = _clientLogic.FinById(id);
            if (clientDTO == null)
            {
                return HttpNotFound();
            }
            return View(clientDTO);
        }

        // GET: Client/Create
        public ActionResult Create()
        {
            ViewBag.ZipcodeDTOId = new SelectList(_zipcodeLogic.GetAll(), "Id", "Zipcodes");
            return View();
        }

        // POST: Client/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,LastName,Vat,Deleted,Email,Adress,ZipcodeDTOId")] ClientDTO clientDTO)
        {
            if (ModelState.IsValid)
            {
                _clientLogic.Add(clientDTO);
                return RedirectToAction("Index");
            }

            ViewBag.ZipcodeDTOId = new SelectList(_zipcodeLogic.GetAll(), "Id", "Id", clientDTO.ZipcodeDTOId);
            return View(clientDTO);
        }

        // GET: Client/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ClientDTO clientDTO = _clientLogic.FinById(id);
            if (clientDTO == null)
            {
                return HttpNotFound();
            }
            ViewBag.ZipcodeDTOId = new SelectList(_zipcodeLogic.GetAll(), "Id", "Zipcodes", clientDTO.ZipcodeDTOId);
            return View(clientDTO);
        }

        // POST: Client/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,LastName,Vat,Deleted,Email,Adress,ZipcodeDTOId")] ClientDTO clientDTO)
        {
            if (ModelState.IsValid)
            {
                _clientLogic.Modify(clientDTO);
                return RedirectToAction("Index");
            }
            ViewBag.ZipcodeDTOId = new SelectList(_zipcodeLogic.GetAll(), "Id", "Zipcodes", clientDTO.ZipcodeDTOId);
            return View(clientDTO);
        }

        // GET: Client/Delete/5
//        public ActionResult Delete(int? id)
//        {
//            if (id == null)
//            {
//                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
//            }
//            ClientDTO clientDTO = db.ClientDTOes.Find(id);
//            if (clientDTO == null)
//            {
//                return HttpNotFound();
//            }
//            return View(clientDTO);
//        }
//
//        // POST: Client/Delete/5
//        [HttpPost, ActionName("Delete")]
//        [ValidateAntiForgeryToken]
//        public ActionResult DeleteConfirmed(int id)
//        {
//            ClientDTO clientDTO = db.ClientDTOes.Find(id);
//            db.ClientDTOes.Remove(clientDTO);
//            db.SaveChanges();
//            return RedirectToAction("Index");
//        }
//
//        protected override void Dispose(bool disposing)
//        {
//            if (disposing)
//            {
//                db.Dispose();
//            }
//            base.Dispose(disposing);
//        }
    }
}

Facturation.WEB.UI/Controllers/ZipcodeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Facturation.BLL;
using Facturation.DAL;
using Facturation.DTO;

namespace Facturation.WEB.UI.Controllers
{
    [Authorize]
    public class ZipcodeController : Controller
    {
        private ZipcodeLogic _zipcodeLogic;

        public ZipcodeController()
        {
            _zipcodeLogic = new ZipcodeLogic();
        }

        // GET: Zipcode
        public ActionResult Index()
        {
            return View(_zipcodeLogic.GetAll());
        }

        // GET: Zipcode/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ZipcodeDTO zipcodeDTO = _zipcodeLogic.FindById(id);
            if (zipcodeDTO == null)
            {
                return HttpNotFound();
            }
            return View(zipcodeDTO);
        }

        // GET: Zipcode/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Zipcode/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Zipcodes")] ZipcodeDTO zipcodeDTO)
        {
            if (ModelState.IsValid)
            {
                _zipcodeLogic.Add(zipcodeDTO);
                return RedirectToAction("Create","Client");
            }

            return View(zipcodeDTO);
        }

        // GET: Zipcode/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            ZipcodeDTO zipcodeDTO = _zipcodeLogic.FindById(id);
            if (zipcodeDTO == null)
            {
                return HttpNotFound();
            }
            return View(zipcodeDTO);
        }

        // POST: Zipcode/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Zipcodes")] ZipcodeDTO zipcodeDTO)
        {
            if (ModelState.IsValid)
            {
                _zipcodeLogic.Modify(zipcodeDTO);
                return RedirectToAction("Index");
            }
            return View(zipcodeDTO);
        }

        // GET: Zipcode/Delete/5
//        public ActionResult Delete(int? id)
//        {
//            if (id == null)
//            {
//                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
//            }
//            ZipcodeDTO zipcodeDTO = db.ZipcodeDTOes.Find(id);
//            if (zipcodeDTO == null)
//            {
//                return HttpNotFound();
//            }
//            return View(zipcodeDTO);
//        }
//
//        // POST: Zipcode/Delete/5
//        [HttpPost, ActionName("Delete")]
//        [ValidateAntiForgeryToken]
//        public ActionResult DeleteConfirmed(int id)
//        {
//            ZipcodeDTO zipcodeDTO = db.ZipcodeDTOes.Find(id);
//            db.ZipcodeDTOes.Remove(zipcodeDTO);
//            db.SaveChanges();
//            return RedirectToAction("Index");
//        }
//
//        protected override void Dispose(bool disposing)
//        {
//            if (disposing)
//            {
//                db.Dispose();
//            }
//            base.Dispose(disposing);
//        }
    }
}

Facturation.WEB.UI/Views/Client/Create.cshtml
@model Facturation.DTO.ClientDTO

@{
    ViewBag.Title = "Create";
}

<h2>Klant aanmaken</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name,"Naam", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName,"Achternaam", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vat,"Btw-nummer", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vat, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Email,"E-mailadres", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adress, "Adres", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ZipcodeDTOId, "Postcode", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ZipcodeDTOId", null, htmlAttributes: new { @class = "form-control" }) | @Html.ActionLink("Postcode toevoegen", "Create", "Zipcode")
                @Html.ValidationMessageFor(model => model.ZipcodeDTOId, "", new { @class = "text-danger" })
                <div class="form-group">

                </div>
            </div>
            
        </div>
        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Aanmaken" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Terug naar overzicht", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Facturation.WEB.UI/Views/Client/Delete.cshtml
@model Facturation.DTO.ClientDTO

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ClientDTO</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ZipcodeDto.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZipcodeDto.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Deleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Adress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adress)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Facturation.WEB.UI/Views/Client/Details.cshtml
@model Facturation.DTO.ClientDTO

@{
    ViewBag.Title = "Details";
}

<h2>Klant details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            Voornaam
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            Achternaam
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            Btw nummer
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vat)
        </dd>

        <dt>
           E-mailadres
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            Adres
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt>
            Postcode
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ZipcodeDto.Zipcodes)
        </dd>

    </dl>
</div>
<p>
    
    <td class="hidden-print">
  
    <a title="Terug naar overzicht" href="@Url.Action("Index", "Client", new {id = Model.Id})">
        <img src="../../Icon/back-arrow.svg" width="20" height="20" /> |
    <a title="Aanpassen" href="@Url.Action("Edit", "Client", new {id = Model.Id})">
        <img src="../../Icon/pencil.svg" width="15" height="15"/>   
    </a>
</p>

Facturation.WEB.UI/Views/Client/Edit.cshtml
@model Facturation.DTO.ClientDTO

@{
    ViewBag.Title = "Edit";
}

<h2>Klant aanpassen</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, "Voornaam", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, "Achternaam", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Vat, "Btwnummer", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Vat, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Vat, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Deleted, "Verwijderen", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Deleted)
                @Html.ValidationMessageFor(model => model.Deleted, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, "E-mailadres", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Adress, "Adres", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Adress, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Adress, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ZipcodeDTOId, "Postcode", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ZipcodeDTOId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ZipcodeDTOId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button title="Opslaan" type="submit" value="Opslaan" style="background-color: transparent;border: none "><img src="../../Icon/save.svg" width="25" height="25" /> Opslaan</button>
        </div>
    </div>
</div>
}

<div>
    <a title="Terug naar overzicht" href="@Url.Action("Index", "Client", new {id = Model.Id})">
        <img src="../../Icon/back-arrow.svg" width="20" height="20" />
    </a> 
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Facturation.WEB.UI/Views/Client/Index.cshtml
@model PagedList.IPagedList<Facturation.DTO.ClientDTO>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
}

<h2>Klanten overzicht</h2>

@using (Html.BeginForm())
{
<p>
    <div align="left" style="float: left">
        <a href="@Url.Action("Create", "Client", null)">
            <img src="../../Icon/pen.svg" width="20" height="20" />Klant aanmaken
        </a>
    </div>
    <div align="right">
        @Html.TextBox("SearchString")
        <button title="Zoeken" input="submit" style="background-color: transparent; border: none"><img src="../../Icon/magnifying-glass.svg" width="20" height="20" /></button>
    </div>
</p>
}
<table class="table table-striped">
    <tr>

        <th>
            @Html.ActionLink("Naam", "Index", new { sortOrder = ViewBag.NameSortParm })
        </th>
        <th>
            Achternaam
        </th>
        <th>
            Btwnummer
        </th>
        <th>
            E-mailadress
        </th>
        <th>
            Adres
        </th>
        <th>
            Postcode
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Vat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Adress)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ZipcodeDto.Zipcodes)
            </td>
            <td>
                @Html.ActionLink("Klant details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Aanpassen", "Edit", new { id = item.Id }) |

            </td>
        </tr>
    }

</table>
<br />

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount