Facturation.WEB.UI/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Facturation.BLL;
using Facturation.DAL;
using Facturation.DTO;
using PagedList;

namespace Facturation.WEB.UI.Controllers
{
    [Authorize]
    public class InvoiceController : Controller
    {
        private InvoiceLogic _invoiceLogic;
        private InvoiceDetailLogic _invoiceDetailLogic;
        private ClientLogic _clientLogic;

        public InvoiceController()
        {
            _clientLogic = new ClientLogic();
            _invoiceLogic = new InvoiceLogic();
            _invoiceDetailLogic = new InvoiceDetailLogic();
        }

        // GET: Invoice
        public ActionResult Index(string sortOrder,string searchString, string currentFilter, int? page)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.SortParm = sortOrder == "Date" ? "date_desc" : "Date";
            var invoices = from invoice in _invoiceLogic.GetActiveInvoices()
                select invoice;
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                invoices = invoices.Where(s => s.ClientDto.Name.Contains(searchString) || s.InvoiceCode.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    invoices = invoices.OrderByDescending(s => s.ClientDto.Name);
                    break;
                case "Date":
                    invoices = invoices.OrderBy(s => s.Date);
                    break;
                case "date_desc":
                    invoices = invoices.OrderByDescending(s => s.InvoiceCode);
                    break;
                default:
                    invoices = invoices.OrderBy(s => s.ClientDto.Name);
                    break;
            }
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(invoices.ToPagedList(pageNumber,pageSize));

//            return View(_invoiceLogic.GetActiveInvoices());
        }

        // GET: Invoice/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            InvoiceDTO invoiceDTO = _invoiceLogic.FindById(id);
            List<InvoiceDetailDTO> detailDtos = _invoiceDetailLogic.GetAll().Where(i => i.InvoiceDTOId == invoiceDTO.Id).ToList();
            invoiceDTO.InvoiceDetails = detailDtos;
            ViewBag.invoice = invoiceDTO;
            ViewBag.TotalPriceWithVAT = _invoiceLogic.GetTotalWithVat(invoiceDTO);
            ViewBag.TotalPriceWithoutVat = _invoiceLogic.GetTotalWithoutVat(invoiceDTO);
            ViewBag.PricesWithoutVat = _invoiceLogic.PriceOfDetailLineOfInvoiceWithoutVat(invoiceDTO);
            ViewBag.PricesWithVat = _invoiceLogic.PriceOfDetailLineOfInvoiceWithVat(invoiceDTO);
            return View(invoiceDTO);
        }

        // GET: Invoice/Create
        public ActionResult Create()
        {
            ViewBag.ClientDTOId = new SelectList(_clientLogic.GetActiveClients(), "Id", "Name");
            return View();
        }

        // POST: Invoice/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Date,InvoiceCode,Deleted,Finished,ClientDTOId")] InvoiceDTO invoiceDTO)
        {
            if (ModelState.IsValid)
            {
                invoiceDTO.InvoiceCode =  _invoiceLogic.GetinvoiceCode(invoiceDTO.Date);
                _invoiceLogic.Add(invoiceDTO);
                return RedirectToAction("Index");
            }

            ViewBag.ClientDTOId = new SelectList(_clientLogic.GetActiveClients(), "Id", "Name", invoiceDTO.ClientDTOId);
            return View(invoiceDTO);
        }

        // GET: Invoice/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            InvoiceDTO invoiceDTO = _invoiceLogic.FindById(id);
            if (invoiceDTO == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClientDTOId = new SelectList(_clientLogic.GetActiveClients(), "Id", "Name", invoiceDTO.ClientDTOId);
            return View(invoiceDTO);
        }

        // POST: Invoice/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Date,InvoiceCode,Deleted,Finished,ClientDTOId")] InvoiceDTO invoiceDTO)
        {
            if (ModelState.IsValid)
            {
                invoiceDTO.InvoiceCode = _invoiceLogic.GetinvoiceCode(invoiceDTO.Date);
                _invoiceLogic.Modify(invoiceDTO);
                return RedirectToAction("Index");
            }
            ViewBag.ClientDTOId = new SelectList(_clientLogic.GetActiveClients(), "Id", "Name", invoiceDTO.ClientDTOId);
            return View(invoiceDTO);
        }

        // GET: Invoice/Delete/5
//        public ActionResult Delete(int? id)
//        {
//            if (id == null)
//            {
//                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
//            }
//            InvoiceDTO invoiceDTO = db.InvoiceDTOes.Find(id);
//            if (invoiceDTO == null)
//            {
//                return HttpNotFound();
//            }
//            return View(invoiceDTO);
//        }
//
//        // POST: Invoice/Delete/5
//        [HttpPost, ActionName("Delete")]
//        [ValidateAntiForgeryToken]
//        public ActionResult DeleteConfirmed(int id)
//        {
//            InvoiceDTO invoiceDTO = db.InvoiceDTOes.Find(id);
//            db.InvoiceDTOes.Remove(invoiceDTO);
//            db.SaveChanges();
//            return RedirectToAction("Index");
//        }
//
//        protected override void Dispose(bool disposing)
//        {
//            if (disposing)
//            {
//                db.Dispose();
//            }
//            base.Dispose(disposing);
//        }
    }
}

Facturation.WEB.UI/Controllers/InvoiceDetailController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Facturation.BLL;
using Facturation.DAL;
using Facturation.DTO;

namespace Facturation.WEB.UI.Controllers
{
    [Authorize]
    public class InvoiceDetailController : Controller
    {
        
        private InvoiceDetailLogic _invoiceDetailLogic;
        private InvoiceLogic _invoiceLogic;

        public InvoiceDetailController()
        {
            _invoiceLogic = new InvoiceLogic();
            _invoiceDetailLogic = new InvoiceDetailLogic();
        }

        // GET: InvoiceDetail
        public ActionResult Index()
        {
            
            return View(_invoiceDetailLogic.GetAll());
        }

        // GET: InvoiceDetail/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            InvoiceDTO invoiceDetailDTO = _invoiceLogic.FindById(id);
            InvoiceDetailDTO invoiceDetailDto = _invoiceDetailLogic.FindById(invoiceDetailDTO.Id);
            ViewBag.priceWithVat = _invoiceDetailLogic.TotalPriceWithVat(invoiceDetailDto);
            ViewBag.priceWithoutVAT = _invoiceDetailLogic.TotalPriceWithoutVat(invoiceDetailDto);
            return View(invoiceDetailDto);
        }

        // GET: InvoiceDetail/Create
        public ActionResult Create(InvoiceDTO invoiceDto)
        {
            
            ViewBag.InvoiceDTOId = new SelectList(_invoiceLogic.GetActiveInvoices().Where(i => i.Id == invoiceDto.Id), "Id", "InvoiceCode");
            return View();

        }

        // POST: InvoiceDetail/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Discount,Price,Pieces,Vat,Name,InvoiceDTOId,TotalPrice,TotalPriceWithoutVat")] InvoiceDetailDTO invoiceDetailDTO)
        {
            if (ModelState.IsValid)
            {
                    _invoiceDetailLogic.Add(invoiceDetailDTO);
                    return RedirectToAction("Details" , "Invoice",new{id = invoiceDetailDTO.InvoiceDTOId});
            }
            ViewBag.InvoiceDTOId = new SelectList(_invoiceLogic.GetActiveInvoices().Where(i => i.Id == invoiceDetailDTO.InvoiceDTOId), "Id", "InvoiceCode", invoiceDetailDTO.InvoiceDTOId);
            return View(invoiceDetailDTO);
        }

        // GET: InvoiceDetail/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            InvoiceDetailDTO invoiceDetailDTO = _invoiceDetailLogic.FindById(id);
            if (invoiceDetailDTO == null)
            {
                return HttpNotFound();
            }
            ViewBag.InvoiceDTOId = new SelectList(_invoiceLogic.GetActiveInvoices(), "Id", "InvoiceCode", invoiceDetailDTO.InvoiceDTOId);
            return View(invoiceDetailDTO);
        }

        // POST: InvoiceDetail/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Discount,Price,Pieces,Vat,Name,InvoiceDTOId,TotalPrice,TotalPriceWithoutVat")] InvoiceDetailDTO invoiceDetailDTO)
        {
            if (ModelState.IsValid)
            {
                _invoiceDetailLogic.Modify(invoiceDetailDTO);
                return RedirectToAction("Details" , "Invoice",new {id = invoiceDetailDTO.InvoiceDTOId});
            }
            ViewBag.InvoiceDTOId = new SelectList(_invoiceLogic.GetActiveInvoices(), "Id", "InvoiceCode", invoiceDetailDTO.InvoiceDTOId);
            return View(invoiceDetailDTO);
        }

        //GET: InvoiceDetail/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            InvoiceDetailDTO invoiceDetailDTO = _invoiceDetailLogic.FindById(id);
            if (invoiceDetailDTO == null)
            {
                return HttpNotFound();
            }
            return View(invoiceDetailDTO);
        }

        // POST: InvoiceDetail/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            InvoiceDetailDTO invoiceDetailDTO = _invoiceDetailLogic.FindById(id);
            _invoiceDetailLogic.Remove(invoiceDetailDTO);
            return RedirectToAction("Details","Invoice",new{invoiceDetailDTO.InvoiceDto.Id});
        }
//
//        protected override void Dispose(bool disposing)
//        {
//            if (disposing)
//            {
//                db.Dispose();
//            }
//            base.Dispose(disposing);
//        }
    }
}

Facturation.WEB.UI/Views/Invoice/Create.cshtml
@model Facturation.DTO.InvoiceDTO

@{
    ViewBag.Title = "Create";
}

<h2>Factuur aanmaken</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Date,"Datum", htmlAttributes: new { @class = "control-label col-md-2" , type="Date"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", type = "Date"} })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.ClientDTOId, "Klantnaam", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClientDTOId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClientDTOId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Aanmaken" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Terug naar overzicht", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Facturation.WEB.UI/Views/Invoice/Delete.cshtml
@model Facturation.DTO.InvoiceDTO

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>InvoiceDTO</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClientDto.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientDto.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InvoiceCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InvoiceCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Deleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Finished)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Finished)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Facturation.WEB.UI/Views/Invoice/Details.cshtml
@using Facturation.DTO
@using Facturation.WEB.UI.Controllers
@model Facturation.DTO.InvoiceDTO

@{
    ViewBag.Title = "Details";
}

<h2>Factuur detail</h2>

<div>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            Datum
        </dt>

        <dd>
            @Model.Date.ToShortDateString()
        </dd>
        <dt>
        <dt>
            Klant
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClientDto.Name)
            @Html.DisplayFor(model => model.ClientDto.LastName)
        </dd>
        <dt>
            Adres
        </dt>
        <dd>
            @Html.DisplayFor(Model => Model.ClientDto.Adress)
            @Html.DisplayFor(model => model.ClientDto.ZipcodeDto.Zipcodes)
        </dd>
        <dt>
            Factuur code
        </dt>
        <dd>
            @Html.DisplayFor(model => model.InvoiceCode)
        </dd>
        <br />
        <table class="table table-striped">
            <tr>
                <th>
                    Aantal stuks
                </th>
                <th>
                    Prijs per stuk
                </th>
                <th>
                    Korting
                </th>
                <th>
                    BTW
                </th>
                <th>
                    Naam product
                </th>

                <th>
                    Prijs excl.
                </th>
                <th>
                    Prijs incl.
                </th>
            </tr>
            @for (int i = 0; i < Model.InvoiceDetails.Count; i++)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.InvoiceDetails.ToList()[i].Pieces) stk.
                </td>
                <td>
                    €@Html.DisplayFor(modelItem => modelItem.InvoiceDetails.ToList()[i].Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.InvoiceDetails.ToList()[i].Discount)%
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.InvoiceDetails.ToList()[i].Vat)%
                </td>
                <td>
                    @Html.DisplayFor(modelItem => modelItem.InvoiceDetails.ToList()[i].Name)
                </td>
                <td>
                    € @ViewBag.PricesWithoutVat[i]
                </td>
                <td>
                    € @ViewBag.PricesWithVat[i]
                </td>
                
                <td class="hidden-print">
                    <a title="Aanpassen" href="@Url.Action("Edit", "InvoiceDetail", new {id = Model.InvoiceDetails[i].Id})">
                    <img src="../../Icon/pencil.svg" width="15" height="15"/>   |
                    <a title="Verwijderen" href="@Url.Action("Delete", "InvoiceDetail", new {id = Model.InvoiceDetails[i].Id})">
                    <img src="../../Icon/trash-alt-solid.svg" width="15" height="15"/></a></a>
                </td>


            </tr>
            }
           
        </table>
    </dl>
</div>
<br />
<div>
        <div>
            <strong style="text-decoration: underline">Totaal</strong>
        </div>
        <h5>
            <strong>Prijs excl: € @ViewBag.TotalPriceWithoutVat </strong>
        </h5>
        <h5>
            <strong>Prijs incl: € @ViewBag.TotalPriceWithVAT </strong>
        </h5>
        <br />
        <div class="hidden-print">
            <p>
                <a title="Factuur Aanpassen" href="@Url.Action("Edit", "Invoice", new {id = Model.Id})">
                    <img src="../../Icon/pencil.svg" width="20" height="20" />
                </a> |
                <a title="Factuur afprinten" href="javascript:window.print()" class="hidden-print">
                    <img src="../../Icon/print.svg" width="20" height="20"/>
                </a> |
                <a title="Terug naar overzicht" href="@Url.Action("Index", "Invoice", new {id = Model.Id})">
                    <img src="../../Icon/back-arrow.svg" width="20" height="20" />
                </a> 
            </p>
        </div>
</div>

Facturation.WEB.UI/Views/Invoice/Edit.cshtml
@model Facturation.DTO.InvoiceDTO

@{
    ViewBag.Title = "Edit";
}

<h2>Factuur Aanpassen</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Date,"Datum",htmlAttributes: new { @class = "control-label col-md-2" ,type = "Date" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" , type = "Date" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            @Html.LabelFor(model => model.Deleted,"Verwijderen",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Deleted)
                    @Html.ValidationMessageFor(model => model.Deleted, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Finished, "Afgerond",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Finished)
                    @Html.ValidationMessageFor(model => model.Finished, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClientDTOId, "Klant", htmlAttributes: new { @style = "display:none" })
            <div class="col-md-10">
                @Html.DropDownList("ClientDTOId", null, htmlAttributes: new { @style = "display:none" })
                @Html.ValidationMessageFor(model => model.ClientDTOId, "", new { @style = "display:none" })
            </div>
        </div>

       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button title="Opslaan" type="submit" value="Opslaan" style ="background-color: transparent;border: none "><img src="../../Icon/save.svg" width="25" height="25" /> Opslaan</button>
            </div>
        </div>
    </div>
}

<div>
    <a title="Terug naar overzicht" href="@Url.Action("Index", "Invoice", new {id = Model.Id})">
        <img src="../../Icon/back-arrow.svg" width="20" height="20" />
    </a> 
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Facturation.WEB.UI/Views/Invoice/Index.cshtml
@model PagedList.IPagedList<Facturation.DTO.InvoiceDTO>
@using PagedList.Mvc;



@{
    ViewBag.Title = "Index";
}

<h2>Facturen</h2>
@using (Html.BeginForm())
{
    <p>
    <div align="left" style="float: left">
                <a href="@Url.Action("Create", "Invoice", null)">
                    <img src="../../Icon/pen.svg" width="20" height="20" />Factuur aanmaken
                </a>
            </div>
            <div align="right">
                @Html.TextBox("SearchString")
                <button title="Zoeken" input="submit" style="background-color: transparent; border: none"><img src="../../Icon/magnifying-glass.svg" width="20" height="20" /></button>
            </div>
    </p>
}
<table class="table table-striped">
    <tr>
        <th>
            @Html.ActionLink("Naam", "Index", new { sortOrder = ViewBag.NameSortParm })
        </th>
        <th>
            @Html.ActionLink("Datum", "Index", new { sortOrder = ViewBag.SortParm })
        </th>
        <th>
            @Html.ActionLink("Factuurcode", "Index", new { sortOrder = ViewBag.SortParm })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ClientDto.Name)
            </td>
            <td>
                @item.Date.ToShortDateString()
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InvoiceCode)
            </td>

            <td>
                @Html.ActionLink("Aanpassen", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Detail lijn toevoegen", "Create", "InvoiceDetail", new { id = item.Id }, null) |

            </td>
        </tr>
    }

</table>
<br />

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount